### ISSUE TITLE
Arrêter l'application proprement

### ISSUE THREAD

**Issue by Deo-Favente** [AsarixLeDev/YtDownloaderApp#10]
Quand on ferme la fenêtre il y a l'erreur suivante + Pas possible de CTRL-C 

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "C:\Users\enzod\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\enzod\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\enzod\Desktop\YtDownloaderApp\main.py", line 342, in <module>
    ex.show()
KeyboardInterrupt

**Comment by AsarixLeDev** [comment]
Je n'ai pas cette erreur non plus. Est-ce encore lié à peut-être un problème de python ou je ne sais pas quoi ? Dans quel contexte ça fait ça ?

**Comment by Deo-Favente** [comment]
> Je n'ai pas cette erreur non plus. Est-ce encore lié à peut-être un problème de python ou je ne sais pas quoi ? Dans quel contexte ça fait ça ?

Quand je ferme la fenêtre avec la croix 😄 Oui c'est pas censé être utilisé mais il faut penser à tout

**Comment by AsarixLeDev** [comment]
> Quand je ferme la fenêtre avec la croix 😄 Oui c'est pas censé être utilisé mais il faut penser à tout

J'ai aucun problème quand je ferme la fenêtre avec la croix 🤔 

Console :
Multithreading with maximum 16 threads

Process finished with exit code 0
