### ISSUE TITLE
win10toast ne marche que sur win10 (lol)

### ISSUE THREAD

**Issue by Deo-Favente** [AsarixLeDev/YtDownloaderApp#13]
Ayant un mac et un win11 c'est un peu une mauvaise idée d'utiliser ce module je pense.

❯ pip install win10toast
Collecting win10toast
  Downloading win10toast-0.9-py2.py3-none-any.whl.metadata (2.1 kB)
Collecting pypiwin32 (from win10toast)
  Downloading pypiwin32-223-py3-none-any.whl.metadata (236 bytes)
Requirement already satisfied: setuptools in /opt/anaconda3/lib/python3.11/site-packages (from win10toast) (68.2.2)
INFO: pip is looking at multiple versions of pypiwin32 to determine which version is compatible with other requirements. This could take a while.
  Downloading pypiwin32-219.zip (4.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 5.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/86/fxjxysn111nfkjm771nymwq80000gn/T/pip-install-59gdgznk/pypiwin32_a97049fa08474e2ca11283e8c5ec4e64/setup.py", line 121
          print "Building pywin32", pywin32_version
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
❯ python -m main
/Users/enzo/Desktop/Work/Projets OS/YtDownloaderApp/main.py:1: DeprecationWarning: 'cgitb' is deprecated and slated for removal in Python 3.13
  import cgitb
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/enzo/Desktop/Work/Projets OS/YtDownloaderApp/main.py", line 13, in <module>
    from win10toast import ToastNotifier
ModuleNotFoundError: No module named 'win10toast'

**Comment by AsarixLeDev** [comment]
win10toast marche pour moi sur windows 11, tu as la bonne version de pip et de python ? J'ai python 3.9

**Comment by Deo-Favente** [comment]
> win10toast marche pour moi sur windows 11, tu as la bonne version de pip et de python ? J'ai python 3.9
Je vais réessayer mais si c'est censé m'afficher des notifs non ça marche pas
