### ISSUE TITLE
Normaliser les noms des fichiers crées

### ISSUE THREAD

**Issue by Deo-Favente** [AsarixLeDev/YtDownloaderApp#16]
Exemple : VLOOKUP with Images in Google Sheets || Image VLOOKUP in Google Sheets
-> vlookup_with_images_in_google_sheets___image_vlookup_in_google_sheets

Pour éviter les problèmes d'encodage / compatibilité

**Comment by AsarixLeDev** [comment]
Pourquoi ?

**Comment by Deo-Favente** [comment]
Parce que ça plait pas à certains OS quand il y a des caractères spéciaux dans les noms des fichiers.

**Comment by AsarixLeDev** [comment]
Should be fixed in commit a7751cf6b4c98c6c02f1406c28f2e3218ac25f9a
