### ISSUE TITLE
Télécharger plusieurs fois la même vidéo dans différents formats casse l'affichage

### ISSUE THREAD

**Issue by Deo-Favente** [AsarixLeDev/YtDownloaderApp#17]
![image](https://github.com/AsarixLeDev/YtDownloaderApp/assets/56390262/0f2cebe3-f995-4c3f-aec1-5096b9a09400)
Title, ici j'ai téléchargé 4 fois la même vidéo dans différents formats vidéos

**Comment by Deo-Favente** [comment]
Les boutons de fermeture sont d'ailleurs totalement cassés dans cette situation.

**Comment by AsarixLeDev** [comment]
Bug réglé depuis un moment, je trouve plus le commit pour le mentionner
