### ISSUE TITLE
Ajouter des nouveaux formats d'encodage

### ISSUE THREAD

**Issue by AsarixLeDev** [AsarixLeDev/YtDownloaderApp#3]
S'assurer que l'encodage déjà mnt est en mp3, et en ajouter d'autres, genre mov pour le format vidéo etc etc

**Comment by Deo-Favente** [comment]
> S'assurer que l'encodage déjà mnt est en mp3
Je confirme que le MP3 marche. Je push prochainement pour les nouveaux formats
